export let vesper = {
    "string": "#b1fce5",
    "variable": "#fff",
    "variable.builtin": "#a0a0a0",
    "function": "#f6c99f",
    "type": "#f6c99f",
    "namespace": "#f6c99f",
    "method": "#f6c99f",
    "function.method": "#f6c99f",
    "function.macro": '#f6c99f',
    "function.builtin": '#f6c99f',
    "constructor": "#f6c99f",
    "identifier": "#A5FCB6",
    "keyword": "#a0a0a0",
    "number": "#b1fce5",
    "constant": '#f6c99f',
    "comment": "#686767",
    "accent_color": "#f6c99f",
    "accent_color2": "#a0a0a0"
};

export let darcula = {
    "identifier": "#abb7c4",
    "field_identifier": "#abb7c4",
    "property_identifier": "#abb7c4",
    "property": "#abb7c4",
    "string": "#6A8759",
    "keyword": "#CC8242",
    "constant": "#83d2fa",
    "number": "#83d2fa",
    "integer": "#83d2fa",
    "float": "#83d2fa",
    "variable.builtin": "#CC8242",
    "function": "#F6C87B",
    "function.call": "#afaff9",
    "function.macro": '#afaff9',
    "method": "#F6C87B",
    "comment": "#707070",
    "namespace": "#abb7c4",
    "type": "#CC8242",
    "tag.attribute": "#c6a5fc",
    "accent_color": "#83d2fa",
    "accent_color2": "#F6C87B"
}

export let edgo = {
    "identifier": "#A5FCB6",
    "field_identifier": "#A5FCB6",
    "property_identifier": "#A5FCB6",
    "property": "#A5FCB6",
    "string": "#F9D992",
    "keyword": "#f992e6",
    "constant": "#f992e6",
    "number": "#f992e6",
    "integer": "#f992e6",
    "float": "#f992e6",
    "variable": "#A5FCB6",
    "variable.builtin": "#f992e6",
    "function": "#afaff9",
    "function.call": "#afaff9",
    "method": "#afaff9",
    "comment": "#767676",
    "namespace": "#c6a5fc",
    "type": "#c6a5fc",
    "tag.attribute": "#c6a5fc",
    "tag": "#c6a5fc",
    "error": "#A5FCB6",
    "accent_color": "#767676",
    "accent_color2": "#F9D992"
}

export let anycode = {
    "string": "#b1fce5",
    "variable": "#fff",
    "variable.builtin": "#a0a0a0",
    "function": "#f6c99f",
    "type": "#f6c99f",
    "namespace": "#f6c99f",
    "method": "#f6c99f",
    "function.method": "#f6c99f",
    "function.macro": '#f6c99f',
    "function.builtin": '#f6c99f',
    "constructor": "#f6c99f",
    "identifier": "#A5FCB6",
    "keyword": "#a0a0a0",
    "number": "#b1fce5",
    "constant": '#f6c99f',
    "comment": "#727171",
    "accent_color": "#A5FCB6",
    "accent_color2": "#a0a0a0"
};

